---
# tasks file for limit_range
- name: set the limit ranges
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ ns_name }}"
    # context: "crc-admin"
    # kubeconfig: "~/.kube/config"

    definition:
      api_version: v1
      kind: LimitRange

      metadata:
        name: cpu-resource-constraint
      spec:
        limits:
        - default: # this section defines default limits
            cpu: 50m
          defaultRequest: # this section defines default requests
            cpu: 50m
          max: # max and min define the limit range
            cpu: "1"
          min:
            cpu: 10m
          type: Container
