---
- name: k8s ns
  hosts: all
  vars:
    myproject: "ansible-examples"
  tasks:
    - name: namespace present
      kubernetes.core.k8s:
        kind: Namespace
        api_version: v1
        name: "{{ myproject }}"
        state: present