---
- name: k8s resource quota
  hosts: all
  tasks:
    - name: set the resource quota
      kubernetes.core.k8s:
        state: "{{ state }}"
        namespace: ansible-examples
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: pods-low
          spec:
            hard:
              cpu: "5"
              memory: 10Gi
              pods: "10"
            scopeSelector:
              matchExpressions:
              - operator : In
                scopeName: PriorityClass
                values: ["low"]